language: python

python:
    - 3.5

dist: trusty

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libboost-all-dev libhdf5-dev

install:
    - pip install -r REQUIREMENTS.txt
    - pip install -e .

script:
    - pytest -v tests/
